CREATE DATABASE ESCOLA;

USE ESCOLA;

CREATE TABLE REGISTRO_ESCOLAR (
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR (1000),
TURMA CHAR (255),
HORARIO CHAR (255),
MATERIA CHAR (255),
NOTA INT,
PRIMARY KEY (ID)
);

INSERT INTO REGISTO_ESCOLAR (NOME, TURMA, HORARIO, MATERIA, NOTA)
VALUE ("Thais", "3A", "Noturno", "Historia", 10);
INSERT INTO REGISTO_ESCOLAR (NOME, TURMA, HORARIO, MATERIA, NOTA)
VALUE ("Raimundo","3B", "Noturno", "Matematico", 10);
INSERT INTO REGISTO_ESCOLAR (NOME, TURMA, HORARIO, MATERIA, NOTA)
VALUE ("Maria", "3C", "Noturno", "Educacao Fisica", 8);
INSERT INTO REGISTO_ESCOLAR (NOME, TURMA, HORARIO, MATERIA, NOTA)
VALUE ("Yun", "2D", "Tarde", "Quimica", 5);
INSERT INTO REGISTO_ESCOLAR (NOME, TURMA, HORARIO, MATERIA, NOTA)
VALUE ("Tainara", "1E", "Tarde", "Portugues", 10);
INSERT INTO REGISTO_ESCOLAR (NOME, TURMA, HORARIO, MATERIA, NOTA)
VALUE ("Yurah", "1C", "Manha", "Ingles", 7);
INSERT INTO REGISTO_ESCOLAR (NOME, TURMA, HORARIO, MATERIA, NOTA)
VALUE ("Luna", "2E", "Tarde", "Geografia", 6);
INSERT INTO REGISTRO_ESCOLAR (NOME, TURMA, HORARIO, MATERIA, NOTA)
VALUE ("Seth", "3F", "Noturno", "Filosofia", 4);

SELECT * FROM REGISTRO_ESCOLAR;
SELECT * FROM REGISTRO_ESCOLAR WHERE NOTA>7;
SELECT * FROM REGISTRO_ESCOLAR WHERE NOTA<7;

SET SQL_SAFE_UPDATES=0;

UPDATE REGISTRO_ESCOLAR SET NOTA = 6 WHERE ID = 8;