CREATE DATABASE E_COMMERCE;

USE E_COMMERCE;

CREATE TABLE PRODUTOS (
ID BIGINT AUTO_INCREMENT,
CATEGORIA CHAR (255),
NOME VARCHAR (1000),
GENERO CHAR (255),
LANCAMENTO INT,
PRECO INT,
PRIMARY KEY (ID)
);

INSERT INTO PRODUTOS (CATEGORIA, NOME, GENERO, LANCAMENTO, PRECO)
VALUE ("Jogo Eletronico", "Genshin Impact", "Aventura", 2020, 650);
INSERT INTO PRODUTOS (CATEGORIA, NOME, GENERO, LANCAMENTO, PRECO)
VALUE ("Jogo Eletronico", "Horizon Zero Dawn", "Mundo Aberto", 2017, 300);
INSERT INTO PRODUTOS (CATEGORIA, NOME, GENERO, LANCAMENTO, PRECO)
VALUE ("Jogo Eletronico", "Final Fantasy XV", "RPG Eletronico", 2016, 200);  
INSERT INTO PRODUTOS (CATEGORIA, NOME, GENERO, LANCAMENTO, PRECO)
VALUE ("Jogo Eletronico", "The Last Of Us", "Sobrevivencia", 2014, 700);
INSERT INTO PRODUTOS (CATEGORIA, NOME, GENERO, LANCAMENTO, PRECO)
VALUE ("Jogo Eletronico", "Fran Bow", "Terror", 2016, 130);
INSERT INTO PRODUTOS (CATEGORIA, NOME, GENERO, LANCAMENTO, PRECO)
VALUE ("Jogo Eletronico", "League Of Legends", "MOBA", 2006, 50);
INSERT INTO PRODUTOS (CATEGORIA, NOME, GENERO, LANCAMENTO, PRECO)
VALUE ("Jogo Eletronico", "DMC Devilmay Cry", "Hack and Slash", 2013, 70);
INSERT INTO PRODUTOS (CATEGORIA, NOME, GENERO, LANCAMENTO, PRECO)
VALUE ("Jogo Eletronico", "Death Stranding", "Aventura", 2019, 600);

SELECT * FROM PRODUTOS;
SELECT * FROM PRODUTOS WHERE PRECO > 500;
SELECT * FROM PRODUTOS WHERE PRECO < 500;

UPDATE PRODUTOS SET PRECO = 850 WHERE ID = 1